services:
  - type: web
    name: drip-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    region: singapore
    healthCheckPath: /graphql
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
